### ISSUE TITLE
Windows 11 Antivirus ругается

### ISSUE THREAD

**Issue by PanSom** [koteyur/eiproxy#1]
Собственно сабж.

**Comment by koteyur** [comment]
Да знаю, ума не приложу что с этим делать. Можно вот тут пробовать community score поднять, но хз поможет ли это:
https://www.virustotal.com/gui/file/60aff356e4c8db6362e8f926426f36e25337d295809d2c4919eef462dcac49cb

**Comment by PanSom** [comment]
А может какой параметр при компилировании и будет норм?

**Comment by koteyur** [comment]
Сомневаюсь, честно говоря. Но даже если и так, то я не знаю какой параметр можно попробовать поменять.

**Comment by koteyur** [comment]
Убрал удаление отладочной информации, которые делали бинарник более лёгким. Количество недовольных антивирусов уменьшилось, но MS и Гугл продолжают ругаться:
https://www.virustotal.com/gui/file/8ef3214f56cc8745444e009faa2b79ef2dd8dd696a1ce3523867a50506d9450f?nocache=1

**Comment by PanSom** [comment]
На предыдущий не жаловалось. Я сам так то не кодер но много раз слышал что если функцию переписать и так далее вплоть до названия переменных(что странно) влияет. Можно тест какой сделать на каком этапе начинает агрится может цикл другой или ещё чёт сделать, он же на паттерны собранного файла агрится.

**Comment by koteyur** [comment]
Ну не, эт очень муторно подобным заниматься. Я напишу в поддержку MS, что их антивирус ругается на безобидную программу, и посмотрим что они скажут. Пытаться переписать код, чтобы подстроиться под них я точно не буду. Тем более, что это полный рандом. Мб им в принципе тулзы на Go под винду не нравятся.

**Comment by PanSom** [comment]
https://www.virustotal.com/gui/file/f8513f41cf1460b6c2c415756f4b02673ce754b625bc84538945c5ede7c5e57c?nocache=1

Эт я у себя скомпилил.

**Comment by koteyur** [comment]
Хмм, ничего себе. Как-то по особому компилил или 1 в 1 как в ридми? Может, ты скомпилил случайно CLI версию с флагами от GUI? Там надо сначала сделать cd в папку gui и потом уже запустить команду go build (я обновил ридми минут 20 назад про то, что надо cd gui делать)

**Comment by koteyur** [comment]
Ого, у последней версии (0.2.1) MS убрали детект: https://www.virustotal.com/gui/file/8ef3214f56cc8745444e009faa2b79ef2dd8dd696a1ce3523867a50506d9450f?nocache=1
Я им даж запрос не отправлял для этого (ещё на прошлый не ответили)

**Comment by koteyur** [comment]
В общем, MS, Google и ещё пара АВ убрали детект (см. последнюю ссылку, это для v0.2.1). Осталось только 3 менее известных антивируса (в поддержку которых я тоже написал). Так что, думаю, что в скором времени, когда антивирусы обновят свои сигнатуры у пользователей, прога будет норм скачиваться и запускаться нормально. Не знаю, будет ли всё гладко со следующими версиями, но думаю, что будет всё ок.

Так что, на этом я пока закрываю ишью.
